language: node_js  #设置语言

sudo: false

node_js:
  - stable

branches:
  only:
    - master

cache:
  apt: true
  # yarn: true
  directories:
    - node_modules
	- $HOME/.npm

before_install: 
  - git config user.name "START_END"  #修改name
  - git config user.email "858965877@qq.com"  #修改email
  # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
  # - curl -o- -L https://yarnpkg.com/install.sh | bash
  # - export PATH=$HOME/.yarn/bin:$PATH
  - cd ..
  - git clone https://github.com/StartEnd/Hexo.git
  - cd Hexo
  # - npm install hexo-cli -g  #安装hexo及插件
  # - npm update
  # - npm install
  - cp -fr ../Blog/* ./source/_posts
  - mv -f ./source/_posts/schedule/*		./source/schedule
  - mv themes/next-reloaded themes/next-reloaded_back
  - git clone https://github.com/theme-next/hexo-theme-next themes/next-reloaded
  - cp -fr themes/next-reloaded_back/_config.yml  themes/next-reloaded/_config.yml
  - cp -fr themes/next-reloaded_back/layout/_partials/footer.swig  themes/next-reloaded/layout/_partials/footer.swig
  

install:
    # 不用yarn的话这里改成 npm i 即可
  # - yarn
  - npm install 
script:
  - hexo clean  #清除
  - hexo generate  #生成

after_script:
  - cp CNAME ./public
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
env:
 global:
   - GH_REF: github.com/StartEnd/StartEnd.github.io.git  #设置GH_REF，注意更改yourname

